### PR TITLE
Makefile.msvc: support Visual Studio 2015 Update 1

### PR DESCRIPTION
**Pull request by chris-araman**
The NMake version has increased with VS2015 Update 1.

### CODE REVIEW

**Comment by daviddrysdale** [comment]
Could you update `test/Makefile.msvc` as well please?

**Comment by daviddrysdale** [comment]
Actually, ignore the previous comment -- I moved the version mapping into a separate file to be included by both, so could you move your update to `msvc_ver.inc` instead please?

**Comment by chris-araman** [comment]
I merged your changes. Would you rather I rebase?

**Comment by daviddrysdale** [comment]
Something looked odd in GitHub with that merge, but cherry-picking the relevant bit seemed to work OK...

**Pull request closed without merging**
