### PR TITLE
Support DNSSEC + DANE

### PR DESCRIPTION
**Pull request by nmav**
This series of patches adds support for DNSSEC + parsing of DANE structures.

Changes:
    To add support for sending a query that will set the flags needed by dnssec I had to add the new ares_create_query2().

These patches do add raw DNSSEC support and DANE. They do not add support for reading the trusted dnssec servers (done as separate pull requests).

### CODE REVIEW

**Comment by bagder** [comment]
Are you still interested in seeing this merged? If so, please rebase this set and we can get the ball going.

**Comment by nmav** [comment]
Done.

**Comment by foxx** [comment]
Any word on whether this will be merged soon?

**Comment by bagder** [comment]
Does it work good for you? Getting feedback or comments on work helps us assess them. Right now it also seems to conflict so that would be neat to see fixed.

**Comment by foxx** [comment]
Sadly my knowledge of DNSSEC is extremely limited so I wouldn't be able to speak with any authority on whether it's functioning as needed. There seems to be significantly less code for DNSSEC related queries in comparison with [ldns](https://www.nlnetlabs.nl/projects/ldns/), but again my lack of DNSSEC understanding makes it difficult to determine if this would be a problem or not. Sorry :/

**Comment by nmav** [comment]
No longer interested in pursuing that.

**Pull request closed without merging**
