### PR TITLE
Parse SOA records from ns_t_any response

### LINKED ISSUE #102: SOA records can't be parsed from a ns_t_any response
I am trying to parse the response of ```ns_t_any``` request records but due to the way ```ares_parse_soa_reply``` is implemented it can't be parsed.

```ares_parse_soa_reply``` explicitly expect the answer record count to be 1 in the answer buffer hence it always returns ```ARES_EBADRESP```, normally it should loop through all the records to find the SOA record if none is found then it should return bad response (as per RFC)

### PR DESCRIPTION
**Pull request by DronRathore**
Closes #102 

Brief: I have added the capability of parsing SOA record from a response buffer of ns_t_any type query, this implementation doesn't interfere with existing T_SOA query's response as that too is treated as a list of records. The function returns ```ARES_EBADRESP``` if no SOA record is found(as per RFC).

The basic idea of sticking to RFC that a ns_t_any too should return an SOA record is something __open for discussion__ but I have kept the functionality intact as it was previously i.e the function returns ARES_EBADRESP if it doesn't find a SOA record regardless of which response it is parsing i.e. T_SOA or T_ANY.

### CODE REVIEW

**Comment by saghul** [comment]
I was about to open an issue which this PR seems to fix. Any chance it gets merged?

**Comment by saghul** [comment]
I don't disagree, but other result parsers seem to work fine, except SOA, so it would be nice to have it work, even if using ANY is discouraged, IMHO.

**Comment by bradh352** [comment]
I don't see any reason not to accept this.  We haven't decided to blacklist use of ANY so proper functionality should be preferred.

**Comment by DronRathore** [comment]
Hey @bradh352 thanks a lot for merging this change! Time for me to pull my side project out from closet after 3 years. However I see that the iOS build is failing for the [latest master on travis](https://travis-ci.org/c-ares/c-ares/jobs/660651727?utm_medium=notification) with timeout error, do you have any insights as in why would that be the case?

I will try to reproduce it locally and push a fix for it if it has been caused by my code.

**Comment by DronRathore** [comment]
Just built it locally post rebase and tests are passing (OSX), seems like it gets stuck at the below stage for quite a while
```
checking types of args and return type for recvfrom...
```
It does takes a lot of time for it (~3-4min) on 32G Catalina OSX, I think the same is the issue with travis too, it's timing out while trying to fetch the libs.

[Test Logs Gist](https://gist.github.com/DronRathore/a5874252b1829c459adf0c0eb0f0ff73).
Should we ignore this? Or is there any action item to perform?

**Comment by bradh352** [comment]
Yeah, Travis builds for Mac/iOS aren't very good.  They're super-slow machines so false-positive  failures are pretty common.  Its not anything with your code.

**Comment by daviddrysdale** [comment]
I've not looked at the code, but it seems like there's a code path in this PR that leads to a double-free somewhere (found by [OSS-Fuzz](https://opensource.google/projects/oss-fuzz)).  I've put the reproducer into #315.

**Pull request merged**
