### PR TITLE
C-ares timeout fix

### PR DESCRIPTION
**Pull request by sachusachin622**
Fix for #541
@bradh352 @bagder Please help me to review
Thanks

### CODE REVIEW

**Comment by bradh352** [comment]
I don't see how changing a per-attempt timeout would solve this problem.

**Comment by sachusachin622** [comment]
> I don't see how changing a per-attempt timeout would solve this problem.

In the context of using Curl, if a timeout of 20 seconds (-m 20 option) is set, while C-ares employs DEFAULT_TIMEOUT as 5000 (5 seconds) and DEFAULT_TRIES as 4, the outcome is as follows: C-ares initiates the sending of requests in a sequence, with intervals determined by an exponential progression. Specifically, C-ares transmits the first request after a 5-second interval, the second request after a 10-second interval, the third request after a 20-second interval, and the fourth request after a 40-second interval. The cumulative time taken to receive a partial query response (IPV4 address) from C-ares to pass it to Curl totals 75 seconds (1 minute and 15 seconds). During this period, Curl, having already elapsed the 20-second timeout, has concluded with a failure response.

**Solution**
From the above explanation of C-ares timeout logic, C-ares should return the partial query response to curl within curl timeout. So that we can derive the timeout of C-ares from timeout of curl.
Timeout of C-ares = ( Timeout of curl / 2^number of retries )

Dividing the curl timeout by 2^number of retries to get Timeout of C-ares because C-ares follows an exponential pattern for sending successive requests.

Example:
Consider curl timeout is 20 seconds and c-ares number of retries is 4 then C-ares timeout value is 

Timeout of C-ares = (Timeout of curl/2^number of retries)

Timeout of C-ares = (20/2^4) = (20/16)

Timeout of C-ares = 1.25 seconds.

C-ares will send request every 1.25 seconds, 2.50 seconds , 5 seconds, and 10 seconds total 18.75 seconds required to send back response to curl. 
C-ares able to send the partial query response back to curl before curl gets time's out, so that it can use the ipv4 address at least and continue with its operations.

**Here is the packet capture for the above example:**

root@[bd05f1ebe90d:/curl-8.2.1#](http://bd05f1ebe90d/curl-8.2.1) time curl -m20 -v http://www.google.com/
* processing: http://www.google.com/
07:08:22.567944 IP bd05f1ebe90d.44543 > 10.174.75.167.domain: 58166+ A? [www.google.com](http://www.google.com/). (32)
07:08:22.568075 IP bd05f1ebe90d.44543 > 10.174.75.167.domain: 37862+ AAAA? [www.google.com](http://www.google.com/). (32)
07:08:22.568758 IP 10.174.75.167.domain > bd05f1ebe90d.44543: 58166* 1/0/0 A 142.250.195.228 (49)
07:08:22.568767 IP 10.174.75.167.domain > bd05f1ebe90d.44543: 58166* 1/0/0 A 142.250.195.228 (49)
07:08:23.818355 IP bd05f1ebe90d.44543 > 10.174.75.167.domain: 37862+ AAAA? [www.google.com](http://www.google.com/). (32)
07:08:26.319154 IP bd05f1ebe90d.44543 > 10.174.75.167.domain: 37862+ AAAA? [www.google.com](http://www.google.com/). (32)
07:08:31.320595 IP bd05f1ebe90d.44543 > 10.174.75.167.domain: 37862+ AAAA? [www.google.com](http://www.google.com/). (32)
*   Trying 142.250.195.228:80...
* Connected to [www.google.com](http://www.google.com/) (142.250.195.228) port 80
> GET / HTTP/1.1


**Please guide me If anything wrong or missing here**

Thanks

**Comment by bradh352** [comment]
your solution is definitely not right, a right-shift of the timeout by number of tries doesn't make any sense.  the proper solution is discussed in #541

**Comment by sachusachin622** [comment]
Closing this PR and raising new PR #548 
Thanks

**Pull request closed without merging**
