### PR TITLE
Create generator-generic-ossf-slsa3-publish.yml

### PR DESCRIPTION
**Pull request by JoftheV**

### CODE REVIEW

**Review by JoftheV — COMMENTED** [review]
Approve

**Comment by bradh352** [comment]
Looks like this is based on https://github.com/slsa-framework/slsa-github-generator/tree/main/internal/builders/generic but you're using the generic template, right?

As far as I can tell, you're supposed to actually modify this template to build the release artifact, then generate provenance for that. 

That means this needs some modification to actually do anything, right?

**Comment by bradh352** [comment]
@JoftheV please respond or I'll need to close this PR

**Review by JoftheV — COMMENTED** [review]
Approve and commit

**Comment by bradh352** [comment]
if I'm not mistaken, this is more like what you're after: https://github.com/bradh352/c-ares/blob/slsa/.github/workflows/package.yml

**Comment by bradh352** [comment]
closing, #906 should address what you're really looking for.

**Pull request closed without merging**
