### PR TITLE
Add OSS-Fuzz fuzzing badge

### PR DESCRIPTION
**Pull request by inferno-chromium**
Adds based on instructions at
https://google.github.io/oss-fuzz/getting-started/new-project-guide/#status-badge

### CODE REVIEW

**Comment by inferno-chromium** [comment]
@bagder - can you please help to review.

**Comment by inferno-chromium** [comment]
@bagder - can you please merge this.

**Comment by bagder** [comment]
I'd rather not. I'm not very involved here at the moment so I prefer to leave that to those who are more present and "in sync" with what's happening.

**Comment by inferno-chromium** [comment]
@bradh352 - can you please check this and merge if ok.

**Pull request merged**
