### PR TITLE
Provide ares_nameser.h as a public interface

### PR DESCRIPTION
**Pull request by felixonmars**
Implements #415.

### CODE REVIEW

**Comment by bradh352** [comment]
* move `src/lib/ares_nameser.h` -> `include/ares_nameser.h`
* in `include/CMakeLists.txt`, need to add the `ares_nameser.h` to the header list
* in `configure.ac` (or one of the .m4 files) need to set `CARES_HAVE_ARPA_NAMESER_H` and `CARES_HAVE_ARPA_NAMESER_COMPAT_H`
* in include/ares_build.h.in need to add the placeholders for `CARES_HAVE_ARPA_NAMESER_H` and `CARES_HAVE_ARPA_NAMESER_COMPAT_H`
* Need to include `ares_build.h` at the top of `ares_nameser.h` in case it is included without first including ares.h or similar.

**Comment by felixonmars** [comment]
I have some trouble trying to understand the autotools part here. Do I need to write a dnl from scratch? Seems that I cannot test it too:

```
$ autoreconf -ifv
<snip>
aclocal: error: too many loops
aclocal: Please contact <bug-automake@gnu.org>.
 at /usr/share/automake-1.16/Automake/Channels.pm line 655.
        Automake::Channels::msg("automake", "", "too many loops") called at /usr/share/automake-1.16/Automake/ChannelDefs.pm line 226
        Automake::ChannelDefs::prog_error("too many loops") called at /usr/bin/aclocal line 1187
autoreconf: error: aclocal failed with exit status: 255
```

**Comment by bradh352** [comment]
There is some issue going on with newer automake versions.  Can you tell me what automake version you have?  We have 2 issues on that #409 and #416.  It would be useful if you could tell me what OS and version of the various tools you are running like those 2 tickets (actually, it would be useful to put the output in the ticket #416) to help isolate.

**Comment by felixonmars** [comment]
It seems to be still broken - the generated ares_build.h still has

```
/* #undef CARES_HAVE_ARPA_NAMESER_H */
/* #undef CARES_HAVE_ARPA_NAMESER_COMPAT_H */
```

While the files are present.

**Comment by felixonmars** [comment]
Okay, I should have done it right this time.

**Pull request merged**
