### PR TITLE
Fix support of link-local IPv6 DNS server in /etc/resolv.conf on macOS.

### PR DESCRIPTION
**Pull request by shpala**
Fix support of link-local IPv6 DNS server in /etc/resolv.conf on macOS.
The issue only happens when using system default link-local IPv6 DNS. Specifying link-local IPv6 DNS address manually works.
Disabling libresolv and using the manual parsing fixes the issue after the change made in #646

On macOS c-ares uses libresolv and assumes that its API res_getservers() fills sin6_scope_id in case of a link-local IPv6 DNS addresses in /etc/resolv.conf.

Unfortunately this is not the case.
See res_getservers() here: https://opensource.apple.com/source/libresolv/libresolv-60/res_init.c.auto.html

### CODE REVIEW

**Comment by bradh352** [comment]
as far as I know, iOS does not have `/etc/resolv.conf` at all, or if it does, its not readable by applications as at one point we had to use libresolv.  Also, libresolv first tries calling `dns_configuration_copy()` then falls back to reading `/etc/resolv.conf`, so likely it never reads from `/etc/resolv.conf` at all, but it is true it looks like it has a bug not reading `if_index` which is indeed populated by `dns_configuration_copy()` which can be found here:

https://opensource.apple.com/source/configd/configd-596.15/dnsinfo/dnsinfo_copy.c.auto.html

The proper solution would be to instead use the functions as found in the above implementation to read the system configuration.   What's interesting is its using a completely different method to fetch DNS config than what I had previously found and sort of put in #642 for reading DNS servers.  I wonder which is better...

**Comment by shpala** [comment]
@bradh352 You're right. I missed that part in iOS.
For now modified the PR to only affect macOS.
I'll look at the real solution you proposed.
Thanks!

**Comment by bradh352** [comment]
I played around with the System Configuration calls `SCDynamicStoreCreate()` and friends and can successfully retrieve all the appropriate DNS information that c-ares currently uses.  However, there's a major caveat, its not able to see the domain-specific resolvers that are used by some VPNs or if a user places a custom config in `/etc/resolver/` which is what #642 is all about which is a shame as the API is much easier to use than the stuff found in the configd source code.

I'll need to play around with the code that utils like `scutil` and `libresolv` use to retrieve the info to see how slim I can get it.

**Comment by bradh352** [comment]
oh wow, this is even more interesting, looks like there is some `macosx.internal` SDK that is required in order to build `libresolv`.

It looks like google chrome works around this by cloning their own `dnsinfo.h`: https://chromium.googlesource.com/chromium/src/+/HEAD/third_party/apple_apsl/dnsinfo.h

And then using `dlopen()` to manually get the symbol for `dns_configuration_copy()`: https://chromium.googlesource.com/chromium/src/+/HEAD/net/dns/dns_config_watcher_mac.cc#32

So we'll probably need to take that same path.

**Comment by bradh352** [comment]
I have a working prototype now, I'll try to get up a proper PR for this tomorrow.

**Comment by bradh352** [comment]
closing in preference of PR #750

**Pull request closed without merging**
