### PR TITLE
Include netinet6/in6.h

### PR DESCRIPTION
**Pull request by farazrbx**
On some platforms, "netinet6/in6.h" is not included by "netinet/in.h" and needs to be included separately.

### CODE REVIEW

**Comment by bradh352** [comment]
We probably need to add this header check to configure.ac and CMakeLists.txt too to set that header definition.  What platform is this?

**Comment by farazrbx** [comment]
> We probably need to add this header check to configure.ac and CMakeLists.txt too to set that header definition.
Added for CMake. Not sure how to add it for configure.ac.

> What platform is this?
Same platform that doesn't have isascii. PlayStation.

**Comment by bradh352** [comment]
For configure.ac you'd just add it to the list here: https://github.com/c-ares/c-ares/blob/main/configure.ac#L419

**Comment by farazrbx** [comment]
@bradh352 Could you review, please?

**Pull request merged**
