### PR TITLE
Test suite and library changes arising from it

### PR DESCRIPTION
**Pull request by daviddrysdale**
For discussion: this pull request contains all of the work on the test suite, with things shuffled so that commits come roughly in the order:
 - library fixes
 - library API changes to improve testability
 - build system changes to support the test code
 - doc changes
 - test code

### CODE REVIEW

**Comment by bagder** [comment]
Thanks for all this hard work @daviddrysdale 

I approve of all the changes done (but I'll state clearly that I did not review the test suite now but that should be fine to merge anyway methinks). I only found a couple of nits that you could opt to fix after you merge this, or before. I let you decide on your own:

- 4f47b17 Mark unhittable lines
- 8f19dfe ahost: Allow repeated -s <domain> options

These two changes add source lines that are longer than 80 columns. We don't have any strong rules or enforcement to keep them shorter than so, but I personally prefer that and most of the existing code already is.

- 7ea64e2 api: Add entrypoints to allow use of per-server ports

This causes 4 new compiler warning for me. I use ` ./configure --enable-maintainer-mode --enable-debug` - the latter option is what enables the picky warnings that might be what make me see them.

**Comment by daviddrysdale** [comment]
Thanks!  I've fixed the nits and pushed the result to master.

I've also updated the badges in `README.md` to point to the master project, but that needs you to turn on integration at [Travis](https://travis-ci.org/), [AppVeyor](https://ci.appveyor.com) and [Coveralls](https://coveralls.io/).

**Comment by bagder** [comment]
Travis and Coveralls should be fine now. I think AppVeyor perhaps needs some time to sync the new state or something, as it doesn't yet offer me to okay repos in the c-ares org. I'll try again in a minute.

**Comment by daviddrysdale** [comment]
Still no sign of AppVeyor -- is anything visible to you?

(Once it's working we'll need to update the `README.md` badge URL, which should be visible at the [Settings/Badges page](https://ci.appveyor.com/project/c-ares/c-ares/settings/badges)).

**Comment by bagder** [comment]
I can't figure out how to add it. The c-ares organization doesn't appear when I want to "create a new project" - in fact only a subset of my orgs do but I have no clue how they are selected out! :-/

**Comment by daviddrysdale** [comment]
http://help.appveyor.com/discussions/questions/1154-appveyor-account-for-github-organizations might be relevant.

**Pull request closed without merging**
