### PR TITLE
IPv6 link-local servers processing

### PR DESCRIPTION
**Pull request by sergvpurik**
Enable support of IPv6 link-local servers. 
Tested on Linux only.

https://github.com/c-ares/c-ares/issues/462

### CODE REVIEW

**Comment by bradh352** [comment]
Can you elaborate more on what this patch is trying to accomplish?  Are you trying to implement LLMNR or something else?

**Comment by sergvpurik** [comment]
@bradh352 
c-ares uses 'ares_inet_pton' to parse nameserver records from OS DNS configuration (/etc/resolv.conf).
So c-ares can't parse a DNS record with IPv6 addresses if a port or/and a network interface are specified.

Examples:
IPv6 record format with a port
[XXXX::XXXX:XXXX]:P

IPv6 record format with an interface
XXXX::XXXX:XXXX%IFNAME

IPv6 record format with a port and an interface
[XXXX::XXXX:XXXX]:P%IFNAME

Also in the case of IPv6 link-local DNS record, a local socket should be bound to an IPv6 link-local address of the local interface.

This PR fixes parsing of the IPv6 records if the port or/and an interface are specified.
Also, it fixes the local socket binding in case of using the IPv6 link-local address.

**Comment by bradh352** [comment]
Can you share the specification enhancements for resolv.conf that allow that syntax?  I know systemd has some 'resolved.conf' file that supports a DNS syntax like that (and also allows things like  #example.com at the end to state to direct queries for that domain to that server).  I can't find where any docs say resolv.conf allows this though.

**Comment by sergvpurik** [comment]
>Can you share the specification enhancements for resolv.conf that allow that syntax?
https://www.ietf.org/rfc/rfc2732.txt

**Comment by sergvpurik** [comment]
About systemd.
[nameserver - is not only an IP address, It also may include a port and/or an interface name.](https://www.freedesktop.org/software/systemd/man/resolved.conf.html)

**Comment by bradh352** [comment]
I don't see anywhere that says resolv.conf supports a bracketed syntax, that's typically only used if you're going to append a port, which resolv.conf doesn't support as far as I can tell.  We would really need to see a specification that updates the resolv.conf format with the modifications you are trying to make.

**Comment by sergvpurik** [comment]
>I can't find where any docs say resolv.conf allows this though.

Actually to fix IPv6 link-local DNS support systems use nameserver format with an interface name specified.

http://lists.cluenet.de/pipermail/ipv6-ops/2014-July/010032.html
https://askubuntu.com/questions/819343/link-local-fe80-addresses-without-scope-make-their-way-into-etc-resolv-conf

**Comment by bradh352** [comment]
@bagder any insight into this?

**Comment by sergvpurik** [comment]
Another example is rdnssd.
As I know it can produce nameserver records with an interface name specified.
https://linux.die.net/man/8/rdnssd
```
rdnssd parses RDNSS options and keeps track of resolvers to write nameservers entries to a [resolv.conf](https://linux.die.net/man/5/resolv.conf)(5) configuration file.
```

**Review by 69Bitch69 — COMMENTED** [review]
http://www.flibustahezeous3.onion

**Comment by bradh352** [comment]
We did end up adding port and bracketed syntax support as we found an openbsd spec for resolv.conf which explicitly allowed it in PR #534.  We also added support for this on MacOS and Windows.

That said, the specific syntax you're stating, while I do find references to it, its just not ever referenced as valid for resolv.conf.  I really think what we need to do is start reading files generated by systemd or network manager on Linux instead of resolv.conf as it seems like resolv.conf is essentially being deprecated and only exists for legacy applications.

**Comment by bradh352** [comment]
Closing for PR #646

**Pull request closed without merging**
