### PR TITLE
Refresh dns servers

### PR DESCRIPTION
**Pull request by MichalBures**
c-ares currently reads system DNS servers only on init therefore any changes by system settings or by other apps made to them after it's been initialized won't be reflected in `ares_get_servers` function.

I've run into this issue in Node.js that's using c-ares for some of its DNS functionality. See my issue there nodejs/help#408

What this pull does is it introduces a simple public function `ares_refresh_servers` that will reload the DNS servers for a given channel by using `init_by_resolv_conf`. Therefore this doesn't change any current behavior and it's up to the user to implement it if they need it.

On the other hand I'd say this is a bug and a correct behavior for `ares_get_servers` is to always return the up to date server list. Which could be achieved by calling the `ares_refresh_servers` at the beginning of `ares_get_servers`.

I'd appreciate some thoughts on what you think is a better solution.

### CODE REVIEW

**Comment by daviddrysdale** [comment]
This doesn't seem like it will be safe to run on a channel that has requests in progress (won't any in-flight responses get lost/confused?).

Rather than calling `ares_refresh_servers()` why not just build a new channel?

**Comment by MichalBures** [comment]
That's a good idea, thank you. For some reason my mind was stuck on working with the main channel only.

Now `ares_get_servers` always creates an empty channel and loads the system DNS. Also the channel argument isn't needed anymore.

```c++
int ares_get_servers(struct ares_addr_node **servers)
{
	ares_channel channel;
	channel = ares_malloc(sizeof(struct ares_channeldata));
	channel->nservers = -1;
	int status = init_by_resolv_conf(channel);
	if (status != ARES_SUCCESS)
		DEBUGF(fprintf(stderr, "Error: init_by_resolv_conf failed: %s\n",
			ares_strerror(status)));
	
	// ...
```

If you are okay with this approach I'll update the PR.

**Comment by daviddrysdale** [comment]
No, we don't want to change `ares_get_servers` -- that would be a major change in the purpose of that entrypoint, and also wouldn't be back-compatible.

**Comment by daviddrysdale** [comment]
Closing for now, because I think it's already possible to do what you need:
 - if you want to refresh the list of servers, just build a fresh channel and use that
 - if you want to find out the system servers, build a fresh channel and do `ares_get_servers` on it.

**Pull request closed without merging**
